version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.22.0
    ports:
      - "4442-4444:4442-4444"
    networks:
      - selenium-grid

  node-chrome:
    image: selenium/node-chrome:4.22.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

  node-firefox:
    image: selenium/node-firefox:4.22.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
